import NoiseGenerator from "../NoiseGenerator.js";export default class NoiseGeneratorPerlin extends NoiseGenerator{constructor(random){super();this.offsetX=random.nextDouble()*256;this.offsetY=random.nextDouble()*256;this.offsetZ=random.nextDouble()*256;this.permutations=[];for(let i=0;i<256;i++){this.permutations[i]=i;}
for(let i=0;i<256;i++){let n=random.nextInt(256-i)+i;let n2=this.permutations[i];this.permutations[i]=this.permutations[n];this.permutations[n]=n2;this.permutations[i+256]=this.permutations[i];}}
fade(t){return t*t*t*(t*(t*6-15)+10);}
lerp(x,a,b){return a+x*(b-a);}
grad(hash,x,y,z){let h=hash&15;let u=h<8?x:y;let v;if(h<4)
v=y;else if(h===12||h===14)
v=x;else
v=z;return((h&1)===0?u:-u)+((h&2)===0?v:-v);}
perlin(x,z){return this.perlinXYZ(x,z,0);}
perlinXYZ(x,y,z){let shiftX=x+this.offsetX;let shiftY=y+this.offsetY;let shiftZ=z+this.offsetZ;let floorX=Math.floor(shiftX);let floorY=Math.floor(shiftY);let floorZ=Math.floor(shiftZ);if(shiftX<floorX){floorX--;}
if(shiftY<floorY){floorY--;}
if(shiftZ<floorZ){floorZ--;}
let x1=floorX&0xff;let y1=floorY&0xff;let z1=floorZ&0xff;shiftX-=floorX;shiftY-=floorY;shiftZ-=floorZ;let u=this.fade(shiftX);let w=this.fade(shiftY);let v=this.fade(shiftZ);let xy=this.permutations[x1]+y1;let xyz=this.permutations[xy]+z1;let xy1z=this.permutations[xy+1]+z1;let xi=this.permutations[x1+1]+y1;let yi=this.permutations[xi]+z1;let zi=this.permutations[xi+1]+z1;return this.lerp(v,this.lerp(w,this.lerp(u,this.grad(this.permutations[xyz],shiftX,shiftY,shiftZ),this.grad(this.permutations[yi],shiftX-1.0,shiftY,shiftZ)),this.lerp(u,this.grad(this.permutations[xy1z],shiftX,shiftY-1.0,shiftZ),this.grad(this.permutations[zi],shiftX-1.0,shiftY-1.0,shiftZ))),this.lerp(w,this.lerp(u,this.grad(this.permutations[xyz+1],shiftX,shiftY,shiftZ-1.0),this.grad(this.permutations[yi+1],shiftX-1.0,shiftY,shiftZ-1.0)),this.lerp(u,this.grad(this.permutations[xy1z+1],shiftX,shiftY-1.0,shiftZ-1.0),this.grad(this.permutations[zi+1],shiftX-1.0,shiftY-1.0,shiftZ-1.0))));}
combined(noise,x1,y1,z1,x2,y2,z2,strengthX,strengthY,strengthZ,frequency){let index=0;let invertFrequency=1.0/frequency;let prevY3=-1;let output1=0;let output2=0;let output3=0;let output4=0;for(let x=0;x<x2;x++){let shiftX=(x1+x)*strengthX+this.offsetX;let floorX=Math.floor(shiftX);if(shiftX<floorX){floorX--;}
let x3=floorX&0xff;shiftX-=floorX;let u=this.fade(shiftX);for(let z=0;z<z2;z++){let shiftZ=(z1+z)*strengthZ+this.offsetZ;let floorZ=Math.floor(shiftZ);if(shiftZ<floorZ){floorZ--;}
let z3=floorZ&0xff;shiftZ-=floorZ;let w=this.fade(shiftZ);for(let y=0;y<y2;y++){let shiftY=(y1+y)*strengthY+this.offsetY;let floorY=Math.floor(shiftY);if(shiftY<floorY){floorY--;}
let y3=floorY&0xff;shiftY-=floorY;let v=this.fade(shiftY);if(y===0||y3!==prevY3){prevY3=y3;let xy=this.permutations[x3]+y3;let xyz=this.permutations[xy]+z3;let xy1z=this.permutations[xy+1]+z3;let xi=this.permutations[x3+1]+y3;let yi=this.permutations[xi]+z3;let zi=this.permutations[xi+1]+z3;output1=this.lerp(u,this.grad(this.permutations[xyz],shiftX,shiftY,shiftZ),this.grad(this.permutations[yi],shiftX-1.0,shiftY,shiftZ));output2=this.lerp(u,this.grad(this.permutations[xy1z],shiftX,shiftY-1.0,shiftZ),this.grad(this.permutations[zi],shiftX-1.0,shiftY-1.0,shiftZ));output3=this.lerp(u,this.grad(this.permutations[xyz+1],shiftX,shiftY,shiftZ-1.0),this.grad(this.permutations[yi+1],shiftX-1.0,shiftY,shiftZ-1.0));output4=this.lerp(u,this.grad(this.permutations[xy1z+1],shiftX,shiftY-1.0,shiftZ-1.0),this.grad(this.permutations[zi+1],shiftX-1.0,shiftY-1.0,shiftZ-1.0));}
let output5=this.lerp(v,output1,output2);let output6=this.lerp(v,output3,output4);let output=this.lerp(w,output5,output6);noise[index++]+=output*invertFrequency;}}}}}