import Timer from "../util/Timer.js";import GameSettings from "./GameSettings.js";import GameWindow from "./GameWindow.js";import WorldRenderer from "./render/WorldRenderer.js";import ScreenRenderer from "./render/gui/ScreenRenderer.js";import ItemRenderer from "./render/gui/ItemRenderer.js";import IngameOverlay from "./gui/overlay/IngameOverlay.js";import SoundManager from "./sound/SoundManager.js";import Block from "./world/block/Block.js";import BoundingBox from "../util/BoundingBox.js";import{BlockRegistry}from "./world/block/BlockRegistry.js";import FontRenderer from "./render/gui/FontRenderer.js";import GrassColorizer from "./render/GrassColorizer.js";import GuiMainMenu from "./gui/screens/GuiMainMenu.js";import GuiLoadingScreen from "./gui/screens/GuiLoadingScreen.js";import*as THREE from "../../../../../libraries/three.module.js";import ParticleRenderer from "./render/particle/ParticleRenderer.js";import GuiChat from "./gui/screens/GuiChat.js";import CommandHandler from "./command/CommandHandler.js";import GuiContainerCreative from "./gui/screens/container/GuiContainerCreative.js";import GameProfile from "../util/GameProfile.js";import UUID from "../util/UUID.js";import FocusStateType from "../util/FocusStateType.js";import Session from "../util/Session.js";import PlayerControllerMultiplayer from "./network/controller/PlayerControllerMultiplayer.js";export default class Minecraft{static VERSION="1.1.8"
static URL_GITHUB="https://github.com/labystudio/js-minecraft";static PROTOCOL_VERSION=47;static PROXY={"address":"localhost","port":30023};constructor(canvasWrapperId,resources){this.resources=resources;this.currentScreen=null;this.loadingScreen=null;this.world=null;this.player=null;this.playerController=null;this.fps=0;this.maxFps=0;this.timer=new Timer(20);this.settings=new GameSettings();this.settings.load();if(this.settings.session===null){let username="Player"+Math.floor(Math.random()*100);let profile=new GameProfile(UUID.randomUUID(),username);this.setSession(new Session(profile,""));}else{this.setSession(Session.fromJson(this.settings.session));}
this.window=new GameWindow(this,canvasWrapperId);this.worldRenderer=new WorldRenderer(this,this.window);this.screenRenderer=new ScreenRenderer(this,this.window);this.itemRenderer=new ItemRenderer(this,this.window);this.ingameOverlay=new IngameOverlay(this,this.window);this.commandHandler=new CommandHandler(this);this.frames=0;this.lastTime=Date.now();BlockRegistry.create();this.itemRenderer.initialize();this.fontRenderer=new FontRenderer(this);this.grassColorizer=new GrassColorizer(this);this.particleRenderer=new ParticleRenderer(this);this.window.updateWindowSize();this.soundManager=new SoundManager();this.displayScreen(new GuiMainMenu());this.init();}
init(){this.running=true;this.requestNextFrame();}
loadWorld(world){if(world===null){this.worldRenderer.reset();this.itemRenderer.reset();if(this.playerController instanceof PlayerControllerMultiplayer){let networkHandler=this.playerController.getNetworkHandler();if(networkHandler.getNetworkManager().isConnected()){networkHandler.getNetworkManager().close();}
this.ingameOverlay.playerListOverlay.setHeader(null);this.ingameOverlay.playerListOverlay.setFooter(null);}
this.playerController=null;if(this.world!==null){this.world.getChunkProvider().getChunks().clear();this.world.clearEntities();this.world=null;this.player=null;this.loadingScreen=null;}
this.displayScreen(new GuiMainMenu());}else{this.loadingScreen=new GuiLoadingScreen();this.loadingScreen.setTitle("Building terrain...");this.displayScreen(this.loadingScreen);if(this.world!==null){this.world.getChunkProvider().getChunks().clear();this.world.clearEntities();this.worldRenderer.reset();this.itemRenderer.reset();}
this.world=world;this.worldRenderer.scene.add(this.world.group);this.player=this.playerController.createPlayer(this.world);this.player.username=this.session.getProfile().getUsername();this.world.addEntity(this.player);this.world.loadSpawnChunks();this.player.respawn();}}
hasInGameFocus(){return this.window.isLocked()&&this.currentScreen===null;}
isInGame(){return this.world!==null&&this.worldRenderer!==null&&this.player!==null;}
addMessageToChat(message){this.ingameOverlay.chatOverlay.addMessage(message);}
requestNextFrame(){requestAnimationFrame(()=>{if(this.running){this.requestNextFrame();this.onLoop();}});}
onLoop(){if(this.isPaused()&&this.isInGame()){let prevPartialTicks=this.timer.partialTicks;this.timer.advanceTime();this.timer.partialTicks=prevPartialTicks;}else{this.timer.advanceTime();}
for(let i=0;i<this.timer.ticks;i++){this.onTick();}
this.onRender(this.timer.partialTicks);this.frames++;while(Date.now()>=this.lastTime+1000){this.fps=this.frames;this.maxFps=Math.max(this.maxFps,this.fps);this.lastTime+=1000;this.frames=0;}}
onRender(partialTicks){if(this.isInGame()){if(this.hasInGameFocus()){let deltaX=this.window.pullMouseMotionX();let deltaY=this.window.pullMouseMotionY();this.player.turn(deltaX,deltaY);}
while(this.world.updateLights()){}
if(this.isInGame()&&!this.isPaused()){this.worldRenderer.render(partialTicks);}}
this.itemRenderer.render(partialTicks);this.screenRenderer.render(partialTicks);}
displayScreen(screen){if(screen===this.currentScreen){return;}
if(typeof screen==="undefined"){console.error("Tried to display an undefined screen");return;}
if(screen===null&&!this.isInGame()){screen=new GuiMainMenu();}
if(this.currentScreen!==null){this.currentScreen.onClose();}
this.currentScreen=screen;this.window.updateWindowSize();if(screen===null){this.window.updateFocusState(FocusStateType.REQUEST_LOCK);}else{this.window.updateFocusState(FocusStateType.REQUEST_EXIT);screen.setup(this,this.window.width,this.window.height);}
this.itemRenderer.rebuildAllItems();}
onTick(){if(this.isInGame()&&!this.isPaused()){this.ingameOverlay.onTick();this.world.onTick();this.worldRenderer.onTick();this.particleRenderer.onTick();}
if(this.currentScreen!==null){this.currentScreen.updateScreen();}
if(this.loadingScreen!==null&&this.isInGame()){let cameraChunkX=Math.floor(this.player.x)>>4;let cameraChunkZ=Math.floor(this.player.z)>>4;let renderDistance=this.settings.viewDistance;let requiredChunks=this.isSingleplayer()?Math.pow(renderDistance*2-1,2):1;let loadedChunks=this.world.getChunkProvider().getChunks().size;setTimeout(()=>{for(let x=-renderDistance+1;x<renderDistance;x++){for(let z=-renderDistance+1;z<renderDistance;z++){this.world.getChunkAt(cameraChunkX+x,cameraChunkZ+z);}}},0);let progress=1/requiredChunks*Math.max(0,loadedChunks-this.world.lightUpdateQueue.length/1000);this.loadingScreen.setProgress(progress);if(progress>=0.99){this.loadingScreen=null;this.displayScreen(null);}}}
onKeyPressed(button){for(let i=1;i<=9;i++){if(button==='Digit'+i){this.player.inventory.selectedSlotIndex=i-1;}}
if(button===this.settings.keyTogglePerspective){this.settings.thirdPersonView=(this.settings.thirdPersonView+1)%3;this.settings.save();}
if(button===this.settings.keyOpenChat){this.displayScreen(new GuiChat());}
if(button==="F3"){this.settings.debugOverlay=!this.settings.debugOverlay;this.settings.save();}
if(button===this.settings.keyOpenInventory){this.displayScreen(new GuiContainerCreative(this.player));}}
onMouseClicked(button){if(this.window.isLocked()){let hitResult=this.player.rayTrace(5,this.timer.partialTicks);if(button===0){if(hitResult!=null){let typeId=this.world.getBlockAt(hitResult.x,hitResult.y,hitResult.z);let block=Block.getById(typeId);if(typeId!==0){let soundName=block.getSound().getBreakSound();this.soundManager.playSound(soundName,hitResult.x+0.5,hitResult.y+0.5,hitResult.z+0.5,1.0,1.0);this.particleRenderer.spawnBlockBreakParticle(this.world,hitResult.x,hitResult.y,hitResult.z);this.world.setBlockAt(hitResult.x,hitResult.y,hitResult.z,0);}}
this.player.swingArm();}
if(button===1){if(hitResult!=null){let typeId=this.world.getBlockAt(hitResult.x,hitResult.y,hitResult.z);if(typeId!==0){for(const item of this.player.inventory.items){const index=this.player.inventory.items.indexOf(item);if(item===typeId&&index<=8){this.player.inventory.selectedSlotIndex=index;return;}}
this.player.inventory.setItemInSelectedSlot(typeId);}}}
if(button===2){if(hitResult!=null){let x=hitResult.x+hitResult.face.x;let y=hitResult.y+hitResult.face.y;let z=hitResult.z+hitResult.face.z;let placedBoundingBox=new BoundingBox(x,y,z,x+1,y+1,z+1);if(!placedBoundingBox.intersects(this.player.boundingBox)){let typeId=this.player.inventory.getItemInSelectedSlot();let prevTypeId=this.world.getBlockAt(x,y,z);if(typeId!==0&&prevTypeId!==typeId){this.world.setBlockAt(x,y,z,typeId);this.player.swingArm();let block=Block.getById(typeId);block.onBlockPlaced(this.world,x,y,z,hitResult.face);let sound=block.getSound();let soundName=sound.getStepSound();this.soundManager.playSound(soundName,hitResult.x+0.5,hitResult.y+0.5,hitResult.z+0.5,1.0,sound.getPitch()*0.8);}}}}
this.worldRenderer.flushRebuild=true;}}
onMouseScroll(delta){if(this.isInGame()){this.player.inventory.shiftSelectedSlot(delta);}}
isPaused(){return!this.hasInGameFocus()&&this.loadingScreen===null&&this.isSingleplayer();}
setSession(session,save=false){this.session=session;if(save){this.settings.session=session.toJson();this.settings.save();}}
updateAccessToken(token){this.session.setAccessToken(token);this.setSession(this.session,true);}
getSession(){return this.session;}
isSingleplayer(){return this.isInGame()&&!(this.playerController instanceof PlayerControllerMultiplayer);}
stop(){if(this.currentScreen!==null){this.currentScreen.onClose();}
this.running=false;this.worldRenderer.reset();this.itemRenderer.reset();this.screenRenderer.reset();this.window.close();}
getThreeTexture(id){if(!(id in this.resources)){console.error("Texture not found: "+id);return;}
let image=this.resources[id];let canvas=document.createElement('canvas');let context=canvas.getContext("2d");canvas.width=image.width;canvas.height=image.height;context.imageSmoothingEnabled=false;context.drawImage(image,0,0,image.width,image.height);return new THREE.CanvasTexture(canvas);}}